### ISSUE TITLE
Maintaining, docs etc

### ISSUE THREAD

**Issue by ivantsov** [ashaffer/redux-subscribe#2]
Hi @ashaffer. Recently I discovered your package because I need to watch for changes in a piece of Redux store. I've started investigating the package and realized that have the following questions:
1. Are you going to maintain the package?
2. Are you going to amend docs and add better example(s)?
3. What's the reason of using `path` and `key` for `subscribe` function?

Thanks in advance :)

**Comment by ashaffer** [comment]
1. Kinda. I don't really have any particular plans to do anything with it at the moment. I'd be happy to give you access if you wanted to make improvements though.
2. I should, i'm not sure when i'll get around to it exactly.
3. So `path` is the path in your redux state atom that you want to listen to. `key` is a unique token used as a handle to the subscription so that you can remove it later.

**Comment by ivantsov** [comment]
Thanks for answering @ashaffer.

So, I can take care of the package and here are the things that I'd like to change:
- get rid off `key` parameter and `unsubscribe` method. It's easier to use closure and return `unsubscribe` function from `subscribe` one (the same way works Redux `store.subscribe`)
- use Jest instead of Tape
- use Airbnb styleguide instead of standard one

If you're don't mind about all these changes and a few others - I can lead the project.

**Comment by ivantsov** [comment]
So, if anybody is interested I've created my own package - https://github.com/ivantsov/redux-subscriber.

Anyway, thanks for your work on this project!
